[tool.towncrier]
filename = "CHANGES.rst"
directory = "news/"
title_format = "{version} ({project_date})"
underlines = ["-", ""]

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking changes:"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "New features:"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug fixes:"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "Internal:"
showcontent = true

[tool.flakeheaven.plugins]
# Disable some checks.
# - E501 line too long
#   flake8 is already testing this, with max-line-length=100000 in .flake8,
#   so pycodestyle should not test it.
# - W503 line break before binary operator
#   Outdated recommendation, see https://www.flake8rules.com/rules/W503.html
mccabe = ["+*"]
pycodestyle = ["+*", "-E501", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]
