name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, "3.10", "3.11"]
        plone: ["6.0.13", "5.2.10"]
        exclude:
          - plone: "5.2.10"
            python: 3.9
          - plone: "5.2.10"
            python: "3.10"
          - plone: "5.2.10"
            python: "3.11"

    steps:
      # git checkout
      - uses: actions/checkout@v2

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      # Install plone.volto with test extras
      - name: Install plone.volto
        run: |
          pip install ".[test]"

      # test
      - name: test
        run: |
          zope-testrunner --auto-color --auto-progress --test-path src
